import { memo } from 'react';
import type { RateLimit } from '../lib/types';

interface FooterProps {
  readonly rateLimit: RateLimit;
  readonly lastUpdated: string;
}

const Footer = memo<FooterProps>(({ rateLimit, lastUpdated }) => {
  const isLowRateLimit = rateLimit.remaining < 100;

  return (
    <footer className="text-center py-8 px-6 bg-white rounded-xl shadow-sm border border-gray-200 animate-fade-in">
      <div className="space-y-1 text-sm text-gray-500">
        <p>
          Generated by{' '}
          <a 
            href="https://github.com/Elcapitanoe" 
            className="text-primary-600 hover:text-primary-700 font-medium transition-colors"
            target="_blank"
            rel="noopener noreferrer"
          >
            @Elcapitanoe
          </a>
          {' • '}
          Config maintained by{' '}
          <a 
            href="https://github.com/0x11DFE" 
            className="text-primary-600 hover:text-primary-700 font-medium transition-colors"
            target="_blank"
            rel="noopener noreferrer"
          >
            @0x11DFE
          </a>
        </p>

        {rateLimit.limit > 0 && (
          <p>
            GitHub API usage:{' '}
            <span className={isLowRateLimit ? 'text-red-600 font-semibold' : 'text-gray-700'}>
              {rateLimit.remaining.toLocaleString()} / {rateLimit.limit.toLocaleString()}
            </span>
            {' • '}
            Resets at: {rateLimit.reset}
          </p>
        )}

        <p className="text-xs">
          Last updated: {lastUpdated}
        </p>
      </div>
    </footer>
  );
});

Footer.displayName = 'Footer';

export default Footer;
