import type { RateLimit } from '../lib/types';

export function Footer(rateLimit: RateLimit, lastUpdated: string): HTMLElement {
  const footer = document.createElement('footer');
  footer.className = 'text-center py-8 px-6 bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-700 animate-fade-in';

  footer.innerHTML = `
    <div class="space-y-1 text-sm text-gray-500 dark:text-gray-400">
      <p>
        Generated by 
        <a 
          href="https://github.com/Elcapitanoe" 
          class="text-primary-600 dark:text-primary-400 hover:text-primary-700 dark:hover:text-primary-300 font-medium transition-colors"
          target="_blank"
          rel="noopener noreferrer"
        >
          @Elcapitanoe
        </a>
        • 
        Config maintained by 
        <a 
          href="https://github.com/0x11DFE" 
          class="text-primary-600 dark:text-primary-400 hover:text-primary-700 dark:hover:text-primary-300 font-medium transition-colors"
          target="_blank"
          rel="noopener noreferrer"
        >
          @0x11DFE
        </a>
      </p>

      <p>
        Last updated: ${lastUpdated}
      </p>
    </div>
  `;

  return footer;
}